---
title: "lasso and rf"
author: "Brianna Carnagie"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, message=FALSE}
library(tidyverse)
library(MatchIt)
library(randomForest)
library(caret)
library(tidyverse)
library(VIM)
library(dplyr)
library(nnet)
library(ranger)
library(progress)
```

```{r cars}
hospital_df = read_csv("/Users/briannacarnagie/Downloads/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2015.csv") %>% janitor::clean_names() |>  filter(grepl("surgical", apr_medical_surgical_description, ignore.case = TRUE))


# Columns to delete
columns_to_delete <- c("health_service_area", "hospital_county", "operating_certificate_number", "facility_id", 
                       "facility_name", "zip_code_3_digits", "discharge_year", "ccs_diagnosis_code", 
                       "ccs_procedure_code", "ccs_procedure_description", 
                       "apr_drg_description", "apr_drg_code", "apr_severity_of_illness_code", "apr_mdc_code", "apr_mdc_description",   
                       "payment_typology_2", "payment_typology_3", "birth_weight", "abortion_edit_indicator", 
                       "emergency_department_indicator", "total_charges", "total_costs")

# Delete columns
hospital_df <- hospital_df[, !(names(hospital_df) %in% columns_to_delete)]

# Deleting NA values
hospital_df<-na.omit(hospital_df)   
```


LOS that were greater than 120 were capped!
```{r}
# Convert columns to factors based on a heuristic (e.g., fewer than 20 unique values)
hospital_df[] <- lapply(hospital_df, function(x) if(length(unique(x)) < 20) factor(x) else x)

# Replace "120 +" with "120"
hospital_df$length_of_stay <- as.character(hospital_df$length_of_stay)
hospital_df$length_of_stay[hospital_df$length_of_stay == "120 +"] <- 120

# Convert the entire column to numeric
hospital_df$length_of_stay <- as.numeric(hospital_df$length_of_stay)

y <- as.numeric(hospital_df$length_of_stay)  # Convert to numeric if it's not already
x <- model.matrix(~ . - length_of_stay, data = hospital_df)  # Exclude the response variable

# Fit the Lasso Model
set.seed(123)
# Use fewer folds in cross-validation (e.g., 5 instead of 10)
cv_lasso <- cv.glmnet(x, y, family = "gaussian", alpha = 1, nfolds = 5)
 # Assuming the response is continuous

# Best lambda
optimal_lambda <- cv_lasso$lambda.min

# Fit final model with optimal lambda
final_lasso_model <- glmnet(x, y, family = "gaussian", alpha = 1, lambda = optimal_lambda)

# Extracting coefficients
coef_lasso <- coef(final_lasso_model, s = "lambda.min")
important_predictors <- coef_lasso[coef_lasso != 0]
print(important_predictors)

if(sum(is.na(x)) > 0) {
  stop("NA values found in predictors; these need to be removed or imputed.")
}

if(sum(is.na(x)) < 1) {
  stop("all good")
}

```

